name: Build and Push to Deployment Repo

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this Repo
        uses: actions/checkout@v4

      - name: Download and Unzip Assets
        run: |
          echo "Downloading assets.zip..."
          curl -L "https://create-rington.com/api/download/assets?code=${{ secrets.DOWNLOAD_ACCESS_CODE }}" -o assets.zip

          echo "Copying assets.zip to server/app/routes/download/"
          mkdir -p server/app/routes/download
          cp assets.zip server/app/routes/download/assets.zip

          echo "Unzipping assets.zip to working directory..."
          unzip -o assets.zip -d ./

          echo "Cleaning up temporary zip..."
          rm assets.zip

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Client
        working-directory: ./client
        run: |
          npm install 
          npm run build

      - name: Prepare output Folder
        run: |
          mkdir -p out/client/dist
          cp -r client/dist/* out/client/dist
          cp -r server out/server

      - name: Rewrite .gitignore for deployment
        run: |
          cat > out/server/.gitignore <<EOF
          /node_modules
          .env
          /services/.env
          /logs/
          /services/logs/
          /stats
          /tmp
          /discord/disabled/
          EOF

      - name: Push to other Repo
        run: |
          cd out
          git init
          git checkout -b main
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/matejhozlar/mc-server-prod.git

          git fetch origin main
          git reset origin/main

          git add .
          git commit -m "Automated deployment on $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
